### PR TITLE
Add go.mod and a basic .gitignore

### PR DESCRIPTION
**Pull request by pablintino**
Add a basic go.mod and .gitignore to get started.

### CODE REVIEW

**Review by evallesp — APPROVED** [review]
Approving as it's the basic version of the file. I see it's the default .gitignore for golang applications.
I'm unsure why some of them are required but I'm OK with this, as we can tweak it later.

**Comment by pablintino** [comment]
@evallesp It's the basic one GH creates, even the operators are using this one that has references to Windows executables.

**Review by frenzyfriday — APPROVED** [review]

**Comment by jguiditta** [comment]
2 questions/thoughts:

1. What is the reason for not using a fork from which to submit pull requests? I know some projects allow patches from branches on the core repository, but usually that is the exception rather than the rule on github (submitting from your personal fork is much more common).
2. What type of commit will be the standard for merging in this repo? Choices from the dropdown are 'squash and merge' (current default), and 'rebase and merge'. 'Merge commit' seems to be disabled, so not that, which I agree with. My personal preference is 'rebase and merge', because then the patch author decides how they want to structure their commits, rather than having them squashed automatically.

The patch itself I have no issues with, just think process should be discussed early to set a standard.

**Pull request merged**
